### ISSUE TITLE
is using keysight visa stable?

### ISSUE THREAD

**Issue by Kerdanyy** [pfroud/JVisa#1]
Hello,

Thank you for this library, I just want to ask if it is stable using Keysight visa as I'm integrating with Keysight product, I've read that it is not the recommended way, but I'm asking if it worked with Keysight visa does this mean it is stable?

**Comment by pfroud** [comment]
Hi,
I don't know how well Keysight VISA works, sorry. I've only tried NI-VISA with JVisa.

If you want to try it, I think the only think you need to do is change `"nivisa64.dll"` to `"agvisa32.dll"` in [JVisaResourceManager.java](https://github.com/pfroud/JVisa/blob/master/src/jvisa/JVisaResourceManager.java#L56).  It looks like that's a 32-bit DLL, and I don't know if that will work either.

All VISA implementations are supposed to work with all instruments which support VISA. So, you could use NI-VISA with your Keysight instrument. However, I don't know what happens if you have multiple VISA implementations installed at the same time.

**Comment by Kerdanyy** [comment]
I have tried it with visa64.dll (keysight's visa dll) and it worked, I just wanted to know if it will be stable.

**Comment by pfroud** [comment]
I don't know. My guess is that if it works at all, it will be very stable.

**Comment by pfroud** [comment]
FYI I've updated JVisa to load a library called "visa32" or "visa64", without any `ni` or `ag` prefix. So you should be able to use Keysight's Visa DLL without any modification to the code. 

Here's the updated file if you want to look:

https://github.com/pfroud/JVisa/blob/371b382c79d58a2c9d78761590d597b80ecbfa29/src/jvisa/JVisaResourceManager.java
